site_name: Azure RemoteApp
site_description: Documentation for Azure RemoteApp
theme_dir: theme
markdown_extensions:
 - admonition

extra_javascript:
- js/extra.js


pages:
- Home: 'index.md'
- Overview:
    - What is Azure RemoteApp?: 'remoteapp-whatis.md'
    - How does licensing work?: 'remoteapp-licensing.md'
    - FAQ: 'remoteapp-faq.md'
    - What's new?: 'remoteapp-whatsnew.md'
    - What's coming?: 'remoteapp-roadmap.md'
    - Azure service limits: 'azure-subscription-service-limits.md'
- Real world scenarios:
    - Run any app on any device: 'remoteapp-anyapp.md'
    - Run Office 365 on any device: 'remoteapp-tutorial-o365anywhere.md'
- Will my app work?:
    - App requirements: 'remoteapp-appreqs.md'
    - OneDrive for Business: 'remoteapp-onedrive.md'
    - SQL Azure: 'remoteapp-sql.md'
    - Office 365: 'remoteapp-o365.md'
    - Outlook 2013: 'remoteapp-outlook.md'
    - Using App-V apps: 'remoteapp-appv.md'
    - QuickBooks on Azure RemoteApp: 'remoteapp-quickbooks.md'
    - Secure apps and resources: 'remoteapp-secure.md'
- Create a RemoteApp collection:
    - Which collection do you need?: 'remoteapp-collections.md'
    - Create a cloud collection: 'remoteapp-create-cloud-deployment.md'
    - Create a hybrid collection: 'remoteapp-create-hybrid-deployment.md'
    - Update your collection: 'remoteapp-update.md'
    - Create a RemoteApp image: 'remoteapp-imageoptions.md'
    - What is in the template image?: 'remoteapp-images.md'
    - Image requirements: 'remoteapp-imagereqs.md'
    - Upload an image: 'remoteapp-uploadimage.md'
    - Create an image from an Azure VM: 'remoteapp-image-on-azurevm.md'
- Configure a Virtual Network:
    - Plan your VNET: 'remoteapp-planvnet.md'
    - Port and URL info: 'remoteapp-ports.md'
    - Validate your VNET: 'remoteapp-vnet.md'
    - Migrate to an Azure VNET: 'remoteapp-migrate.md'
- Publish applications:
    - How to publish an app: 'remoteapp-publish.md'
- Manage Users:
    - How to add users: 'remoteapp-user.md'
    - Configure Active Directory: 'remoteapp-ad.md'
    - Change the Azure AD tenant: 'remoteapp-changetenant.md'
    - Office 365 user accounts: 'remoteapp-o365user.md'
    - Secure Data: 'remoteapp-secureaccess.md'
    - User data: 'remoteapp-upd.md'
- Client experience:
    - Supported clients: 'remoteapp-clients.md'
    - Configure redirection: 'remoteapp-redirection.md'
    - Client best practices: 'remoteapp-bestpractices.md'
- Automate RemoteApp:
    - RemoteApp PowerShell cmdlets: 'remoteapp-tutorial-arawithpowershell.md'
    - Manage RemoteApp with Azure Automation: 'automation-manage-remote-app.md'
- Troubleshoot:
    - Troubleshoot a hybrid collection: 'remoteapp-hybridtrouble.md'
    - Troubleshoot a cloud collection: 'remoteapp-cloudtrouble.md'
